<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>72e9caf8-7c0b-4cf1-990b-5079be0dcab1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='OMS-Module-view']/div[2]/div/div/div/div/div/div/resource-tree/div[2]/div[2]/paged-treeview/div/treenode/treenode/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.toggle-expand-icon.expand-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>24d01ebc-cee6-464f-915c-50ffea6956ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>f6149f42-8aa9-4ce7-9b95-a118c0d235b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>toggle-expand-icon expand-icon</value>
      <webElementGuid>612947b1-b39b-4ebe-8673-48f8a365424f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>▶</value>
      <webElementGuid>4c20388f-a350-45e9-8c8a-972fe59317d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OMS-Module-view&quot;)/div[@class=&quot;content-div col-sm-12 col-xs-12 no-padding&quot;]/div[@class=&quot;container-fluid no-padding oms-main-container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 witsml-main-module-container no-padding&quot;]/div[@class=&quot;col-md-12 acl-content-outer-container no-padding&quot;]/div[@class=&quot;acl-content-container&quot;]/div[@class=&quot;left-content-block&quot;]/resource-tree[1]/div[@class=&quot;resource-tree-outer-container ui-resizable&quot;]/div[@class=&quot;resource-tree-container&quot;]/paged-treeview[1]/div[@class=&quot;pvu-treeview-container&quot;]/treenode[1]/treenode[1]/div[@class=&quot;treenode&quot;]/div[1]/a[@class=&quot;toggle-expand-icon expand-icon&quot;]</value>
      <webElementGuid>9ffd7691-ead8-4258-9197-56b41931de6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='OMS-Module-view']/div[2]/div/div/div/div/div/div/resource-tree/div[2]/div[2]/paged-treeview/div/treenode/treenode/div/div/a</value>
      <webElementGuid>cedfd2d8-5f73-47a3-9a91-1716d212cfc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'▶')]</value>
      <webElementGuid>a0fbc9b8-f484-4f75-a2bf-941619482038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//treenode/div/div/a</value>
      <webElementGuid>abd847b0-7dde-4c78-aa26-cdd3fbc557ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '▶' or . = '▶')]</value>
      <webElementGuid>8c0ef105-f86e-41ee-9812-a68b1ee05527</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
