<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ALL</name>
   <tag></tag>
   <elementGuidId>15543596-133c-4489-b94f-9f45e569dee6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='OMS-Module-view']/div[2]/div/div/div/div/div/div/resource-tree/div[2]/div/div/a[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.tab-all</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dd231ab1-14de-486c-8484-ab4094b0c0b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tab-all</value>
      <webElementGuid>73b0d108-0afd-4b4d-9f5a-a72e7033eb83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-klass</name>
      <type>Main</type>
      <value>tab-all</value>
      <webElementGuid>331413fa-8b08-46ee-a8a0-70657a4efc44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>44975804-f14a-438c-9155-66b8301b3a1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ALL</value>
      <webElementGuid>6c038f2c-0bad-48b2-908c-2b947edea465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OMS-Module-view&quot;)/div[@class=&quot;content-div col-sm-12 col-xs-12 no-padding&quot;]/div[@class=&quot;container-fluid no-padding oms-main-container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 witsml-main-module-container no-padding&quot;]/div[@class=&quot;col-md-12 acl-content-outer-container no-padding&quot;]/div[@class=&quot;acl-content-container&quot;]/div[@class=&quot;left-content-block&quot;]/resource-tree[1]/div[@class=&quot;resource-tree-outer-container ui-resizable&quot;]/div[@class=&quot;resource-tree-toolbar&quot;]/div[@class=&quot;resource-tree-tab-container&quot;]/a[@class=&quot;tab-all&quot;]</value>
      <webElementGuid>66e10776-1070-4dda-9b8a-04a25c033516</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='OMS-Module-view']/div[2]/div/div/div/div/div/div/resource-tree/div[2]/div/div/a[3]</value>
      <webElementGuid>51663271-c212-4f9b-8d1f-062a2e66153c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ALL')]</value>
      <webElementGuid>34d8d2e8-fcf8-486d-9ee6-097a51351b5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>93eff7d9-058d-46ce-bca6-e9ca6d9add7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'ALL' or . = 'ALL')]</value>
      <webElementGuid>b6fc10d9-5e29-46b1-bdbd-966be89aca46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
