<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Groups</name>
   <tag></tag>
   <elementGuidId>e794a8c3-f72a-4010-96b1-7ca57c2cf364</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='assignment-usergroups-container']/div/div/custom-selectbox/pvu-dropdown/div/div[2]/div[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.dropdown-list-item.Groups > a.item-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>85e25fff-5d10-4b9f-b61d-0773c4d55e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-text</value>
      <webElementGuid>badc9a8d-def2-4c5f-bfb7-e70a963470aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Groups</value>
      <webElementGuid>75986420-d7c1-4bc1-94d7-4bbf18851bea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;assignment-usergroups-container&quot;)/div[@class=&quot;userlist-top-container&quot;]/div[@class=&quot;custom-filter-view&quot;]/custom-selectbox[@class=&quot;custom-selectbox-host&quot;]/pvu-dropdown[1]/div[@class=&quot;pvu-dropdown&quot;]/div[@class=&quot;dropdown-list open&quot;]/div[@class=&quot;dropdown-list-item Groups&quot;]/a[@class=&quot;item-text&quot;]</value>
      <webElementGuid>ccd7cb37-df94-4e30-a75d-84fd02d8caa8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='assignment-usergroups-container']/div/div/custom-selectbox/pvu-dropdown/div/div[2]/div[3]/a</value>
      <webElementGuid>2a4259fd-5bef-4219-92eb-d27de9a70e7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Groups')]</value>
      <webElementGuid>f6592c97-dcdd-435a-8acf-156f78d574a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/a</value>
      <webElementGuid>7791aacc-8c83-4e53-b8e1-a695d9479bfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Groups' or . = 'Groups')]</value>
      <webElementGuid>fe9860b7-dd1f-4e5e-be87-0534c953ea63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
