<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_idm</name>
   <tag></tag>
   <elementGuidId>1ba47279-8314-4b24-b40e-1b03a62131aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='OMS-Module-view']/div[2]/div/div/div/div/div/div/resource-tree/div[2]/div[2]/paged-treeview/div/treenode/treenode/treenode[6]/div/div/custom-treenode/resource-treelink/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>treenode:nth-of-type(6) > div.treenode > div > custom-treenode > resource-treelink > div.tree-link-holder > div.None.closed.treeNodeItemCls > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>26fb9330-3983-4121-a683-60b3a5d51046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-inner-h-t-m-l</name>
      <type>Main</type>
      <value>idm</value>
      <webElementGuid>dd482e9a-7baa-485a-810c-14266815730f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>idm</value>
      <webElementGuid>e8202180-186f-4562-83a2-d741fad3e25d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OMS-Module-view&quot;)/div[@class=&quot;content-div col-sm-12 col-xs-12 no-padding&quot;]/div[@class=&quot;container-fluid no-padding oms-main-container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 witsml-main-module-container no-padding&quot;]/div[@class=&quot;col-md-12 acl-content-outer-container no-padding&quot;]/div[@class=&quot;acl-content-container&quot;]/div[@class=&quot;left-content-block&quot;]/resource-tree[1]/div[@class=&quot;resource-tree-outer-container ui-resizable&quot;]/div[@class=&quot;resource-tree-container&quot;]/paged-treeview[1]/div[@class=&quot;pvu-treeview-container&quot;]/treenode[1]/treenode[1]/treenode[6]/div[@class=&quot;treenode&quot;]/div[1]/custom-treenode[1]/resource-treelink[1]/div[@class=&quot;tree-link-holder&quot;]/div[@class=&quot;None closed treeNodeItemCls&quot;]/a[1]</value>
      <webElementGuid>e61bd186-1e13-4fcd-9eab-b9bc9e002115</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='OMS-Module-view']/div[2]/div/div/div/div/div/div/resource-tree/div[2]/div[2]/paged-treeview/div/treenode/treenode/treenode[6]/div/div/custom-treenode/resource-treelink/div/div/a</value>
      <webElementGuid>71a0835a-6efd-4331-b1e2-cd094553ce84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'idm')]</value>
      <webElementGuid>0e10eee6-bdee-470a-8af0-de161ae39f89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//treenode[6]/div/div/custom-treenode/resource-treelink/div/div/a</value>
      <webElementGuid>46a88bca-5ee9-49da-b1c0-b17d8914f219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'idm' or . = 'idm')]</value>
      <webElementGuid>d0d196b1-a242-455d-a236-b92fafe2d97b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
