<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Save</name>
   <tag></tag>
   <elementGuidId>be1e7dc2-aa1b-4936-8ef7-5b1be0c12851</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='OMS-Module-view']/div[2]/div/div/div/div/div/div[3]/div[2]/acl-assignment/div[4]/div[2]/div[3]/pvu-grid/div/grid-footer/div/div[3]/div/toolbar-bttn[2]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.tool-bttn.btn.dynamic-btn.acl-assignment-save-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e58b3eaf-1645-4878-9da3-570ca2f5f6b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tool-bttn btn dynamic-btn acl-assignment-save-btn</value>
      <webElementGuid>b5113f97-4428-4a1b-be5e-f4e847e51aa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-klass</name>
      <type>Main</type>
      <value>tool-bttn btn</value>
      <webElementGuid>04663274-e013-49f9-b3c2-40b03779e133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>dynamic-btn btn acl-assignment-save-btn</value>
      <webElementGuid>60688f3e-3469-400e-adeb-0f1e27653c5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-title</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>6e28bd09-ed5e-45d0-9d04-76865b42c819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>079bb364-d503-464c-9e4e-1f919354e33e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>8b7cc033-3455-41c9-b5bb-6d5db6734a7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OMS-Module-view&quot;)/div[@class=&quot;content-div col-sm-12 col-xs-12 no-padding&quot;]/div[@class=&quot;container-fluid no-padding oms-main-container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 witsml-main-module-container no-padding&quot;]/div[@class=&quot;col-md-12 acl-content-outer-container no-padding&quot;]/div[@class=&quot;acl-content-container&quot;]/div[@class=&quot;main-content-block&quot;]/div[@class=&quot;main-content-container&quot;]/acl-assignment[@class=&quot;pull-left&quot;]/div[@class=&quot;assignment-view-container col-sm-12 no-padding&quot;]/div[@class=&quot;assignment-container&quot;]/div[@class=&quot;assignment-acldetails-container&quot;]/pvu-grid[@class=&quot;basicGidView&quot;]/div[@class=&quot;pvu-grid-container&quot;]/grid-footer[@class=&quot;grid-header-loaded&quot;]/div[@class=&quot;grid-toolbar grid-footer-toolbar&quot;]/div[@class=&quot;grid-action-toolbar&quot;]/div[@class=&quot;footer-tool-bttns&quot;]/toolbar-bttn[2]/div[@class=&quot;grid-toolbar-btn btn&quot;]/a[@class=&quot;tool-bttn btn dynamic-btn acl-assignment-save-btn&quot;]</value>
      <webElementGuid>48ec6ba3-e894-4333-813b-bcfd2520bb8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='OMS-Module-view']/div[2]/div/div/div/div/div/div[3]/div[2]/acl-assignment/div[4]/div[2]/div[3]/pvu-grid/div/grid-footer/div/div[3]/div/toolbar-bttn[2]/div/a</value>
      <webElementGuid>ea46e0e1-d075-4b9e-b1c8-e3e01b5306ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Save')])[2]</value>
      <webElementGuid>4d72e673-2de7-4602-9e2b-07e6786a410e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/toolbar-bttn[2]/div/a</value>
      <webElementGuid>12f5dfcb-6d7f-4daa-a898-589cd9be65f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Save' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>a89ae99d-7a6e-4a2a-b007-677232a3739e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
