<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_user-list-close-btn</name>
   <tag></tag>
   <elementGuidId>9ddfd12c-7943-438f-a5e4-9f3d667665dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='assignment-usergroups-container']/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.user-list-close-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>471a0ce7-a846-4600-ba4a-7e353522bd3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>user-list-close-btn</value>
      <webElementGuid>2f37c8a4-3038-4df8-82ab-23c04173c9ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>0255b2cf-b31b-4255-858d-ff25615b6114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;assignment-usergroups-container&quot;)/div[@class=&quot;userlist-top-container&quot;]/a[@class=&quot;user-list-close-btn&quot;]</value>
      <webElementGuid>83a4c97c-3d7b-4ea0-b3b0-fb621f4572d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='assignment-usergroups-container']/div/a</value>
      <webElementGuid>24df13ee-c77c-4168-bd8c-56bc477cc9c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>5c208269-1772-4771-840d-c349d5104c51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/a</value>
      <webElementGuid>3b71f9a5-0def-49b2-ac98-b112615e3383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#']</value>
      <webElementGuid>fdeeb0c0-ec31-4d83-9008-75c73d82c167</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
