<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Never</name>
   <tag></tag>
   <elementGuidId>1f2663e5-e37d-4036-a6af-95f9255ede87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='OMS-Module-view']/div[2]/div/div/div/div/div/div[3]/div[2]/acl-assignment/div[4]/div[2]/div[3]/pvu-grid/div/div[2]/grid-body/table/tbody/tr[3]/td[10]/grid-cell/formatter-component-cell/selectbox-cell/div/pvu-dropdown/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr.row-new.editable.row-data.active > td.grid-cell.for-onCreateChild > grid-cell.select-box-grid-cell > formatter-component-cell > selectbox-cell.selectbox-host > div.select-box-dropdown-holder > pvu-dropdown > div.pvu-dropdown > div.select-bttn > div.selected-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cf20bc44-83ed-4c52-9b5e-88d03ef519ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selected-text</value>
      <webElementGuid>a8565ebc-fd4e-4e07-9ae3-bf6756c3e964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Never
                </value>
      <webElementGuid>df61ccf3-cea3-4608-87e1-3e429e722520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OMS-Module-view&quot;)/div[@class=&quot;content-div col-sm-12 col-xs-12 no-padding&quot;]/div[@class=&quot;container-fluid no-padding oms-main-container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 witsml-main-module-container no-padding&quot;]/div[@class=&quot;col-md-12 acl-content-outer-container no-padding&quot;]/div[@class=&quot;acl-content-container&quot;]/div[@class=&quot;main-content-block&quot;]/div[@class=&quot;main-content-container&quot;]/acl-assignment[@class=&quot;pull-left&quot;]/div[@class=&quot;assignment-view-container col-sm-12 no-padding&quot;]/div[@class=&quot;assignment-container&quot;]/div[@class=&quot;assignment-acldetails-container&quot;]/pvu-grid[@class=&quot;basicGidView&quot;]/div[@class=&quot;pvu-grid-container&quot;]/div[@class=&quot;grid-body-container&quot;]/grid-body[1]/table[@class=&quot;grid-body table table-bordered table-hover&quot;]/tbody[1]/tr[@class=&quot;row-new editable row-data active&quot;]/td[@class=&quot;grid-cell for-onCreateChild&quot;]/grid-cell[@class=&quot;select-box-grid-cell&quot;]/formatter-component-cell[1]/selectbox-cell[@class=&quot;selectbox-host&quot;]/div[@class=&quot;select-box-dropdown-holder&quot;]/pvu-dropdown[1]/div[@class=&quot;pvu-dropdown&quot;]/div[@class=&quot;select-bttn&quot;]/div[@class=&quot;selected-text&quot;]</value>
      <webElementGuid>4ae29531-2137-4a3a-8aed-28b8524461fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='OMS-Module-view']/div[2]/div/div/div/div/div/div[3]/div[2]/acl-assignment/div[4]/div[2]/div[3]/pvu-grid/div/div[2]/grid-body/table/tbody/tr[3]/td[10]/grid-cell/formatter-component-cell/selectbox-cell/div/pvu-dropdown/div/div/div</value>
      <webElementGuid>3a96323c-a02e-409a-8d84-1233d6143d3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[10]/grid-cell/formatter-component-cell/selectbox-cell/div/pvu-dropdown/div/div/div</value>
      <webElementGuid>307a1b96-4475-4e0a-a368-405bd3addb69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                    Never
                ' or . = '
                    Never
                ')]</value>
      <webElementGuid>8f03bf89-be7d-4f6c-a272-6eb857704f54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
