<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_All</name>
   <tag></tag>
   <elementGuidId>151ed187-e13f-4dc5-94d4-ca1ef35fd947</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='assignment-usergroups-container']/div/div/custom-selectbox/pvu-dropdown/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.custom-filter-view > custom-selectbox.custom-selectbox-host > pvu-dropdown > div.pvu-dropdown > div.select-bttn > div.selected-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>37067be1-371e-4dad-8d5f-11092888cad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selected-text</value>
      <webElementGuid>ede784e9-d4e7-4c00-bc7f-c391effece21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    All
                </value>
      <webElementGuid>5fafe77a-c75a-4068-9f0c-bcb0372c1c7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;assignment-usergroups-container&quot;)/div[@class=&quot;userlist-top-container&quot;]/div[@class=&quot;custom-filter-view&quot;]/custom-selectbox[@class=&quot;custom-selectbox-host&quot;]/pvu-dropdown[1]/div[@class=&quot;pvu-dropdown&quot;]/div[@class=&quot;select-bttn&quot;]/div[@class=&quot;selected-text&quot;]</value>
      <webElementGuid>62e8f9ed-7899-4b46-8b49-f635288c5e85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='assignment-usergroups-container']/div/div/custom-selectbox/pvu-dropdown/div/div/div</value>
      <webElementGuid>f54f5817-f143-4a52-b2d5-af7724b6e49e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/custom-selectbox/pvu-dropdown/div/div/div</value>
      <webElementGuid>aaf94a3a-ba59-4317-a5f9-269402363c70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                    All
                ' or . = '
                    All
                ')]</value>
      <webElementGuid>970182f1-946b-4764-ab4f-76f8ac513ffc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
