<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CheckBoxInput_3</name>
   <tag></tag>
   <elementGuidId>5d465c9a-1a04-43a3-89c0-102bbd2858bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr.row-new.editable.row-data > td.grid-cell.for-Create > grid-cell > formatter-component-cell > checkbox-cell > div.custom-CheckBoxHolder > input.custom-CheckBoxInput.enabled.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[23]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b816d186-5e1b-4e53-9feb-e9bac57a4d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6cda6dd1-c0a1-4ee9-ac41-13a6119f9609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-model</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8789e748-f466-40e0-993e-35b5909888d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-class-name</name>
      <type>Main</type>
      <value>custom-CheckBoxInput enabled</value>
      <webElementGuid>3a4975c8-c9dd-4b50-aaf5-04b934ea9368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-CheckBoxInput enabled ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>ff651e82-fe70-4922-b968-feff1d5860ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OMS-Module-view&quot;)/div[@class=&quot;content-div col-sm-12 col-xs-12 no-padding&quot;]/div[@class=&quot;container-fluid no-padding oms-main-container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 witsml-main-module-container no-padding&quot;]/div[@class=&quot;col-md-12 acl-content-outer-container no-padding&quot;]/div[@class=&quot;acl-content-container&quot;]/div[@class=&quot;main-content-block&quot;]/div[@class=&quot;main-content-container&quot;]/acl-assignment[@class=&quot;pull-left&quot;]/div[@class=&quot;assignment-view-container col-sm-12 no-padding&quot;]/div[@class=&quot;assignment-container&quot;]/div[@class=&quot;assignment-acldetails-container&quot;]/pvu-grid[@class=&quot;basicGidView&quot;]/div[@class=&quot;pvu-grid-container&quot;]/div[@class=&quot;grid-body-container&quot;]/grid-body[1]/table[@class=&quot;grid-body table table-bordered table-hover&quot;]/tbody[1]/tr[@class=&quot;row-new editable row-data&quot;]/td[@class=&quot;grid-cell for-Create&quot;]/grid-cell[1]/formatter-component-cell[1]/checkbox-cell[1]/div[@class=&quot;custom-CheckBoxHolder&quot;]/input[@class=&quot;custom-CheckBoxInput enabled ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>10a0e1f6-24b6-4d0d-bce2-ecff3d129ee2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[21]</value>
      <webElementGuid>a2bce9b8-898f-4549-a61a-ce72929b3257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='OMS-Module-view']/div[2]/div/div/div/div/div/div[3]/div[2]/acl-assignment/div[4]/div[2]/div[3]/pvu-grid/div/div[2]/grid-body/table/tbody/tr[3]/td[5]/grid-cell/formatter-component-cell/checkbox-cell/div/input</value>
      <webElementGuid>f1f80187-5df3-47e3-b2fe-c9948c1a55ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[5]/grid-cell/formatter-component-cell/checkbox-cell/div/input</value>
      <webElementGuid>2a792254-3c76-44d6-803e-bf52d94c9645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>7e508766-2239-44d5-a646-283cfde4f7cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
