<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_form-control input-sm input-textCls s_69fb31</name>
   <tag></tag>
   <elementGuidId>44bfaa35-69b7-471e-a9af-5a381f917f55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.form-control.input-sm.input-textCls.serverUrl.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d19f661e-18a6-469a-9685-70adb1bacbfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm input-textCls serverUrl ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>5f2d8c25-dc71-44f8-b1af-32cc1208926e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Url</value>
      <webElementGuid>70aa22f1-3037-4bdf-a4cb-ceefb86872dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aa6dd6e5-9c56-473f-acd5-ee7797305996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ServerDisplayTable&quot;)/tr[@class=&quot;new-config-add&quot;]/td[2]/div[1]/input[@class=&quot;form-control input-sm input-textCls serverUrl ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>fa3e3746-e9d4-428e-b953-8a332f435d34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[2]</value>
      <webElementGuid>44c27d88-ff3e-453b-9a2a-ec1a7b84debb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='ServerDisplayTable']/tr/td[2]/div/input</value>
      <webElementGuid>6c2212e0-a985-4d68-96e5-b2a90cce8844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/input</value>
      <webElementGuid>dc1e6a56-6408-4499-bb53-0961057324aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter Url' and @type = 'text']</value>
      <webElementGuid>0c56ec23-b0c9-436a-a01e-1d8ac90816b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
