<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CheckBoxInput_1</name>
   <tag></tag>
   <elementGuidId>fff433e5-0685-4231-943c-554243ae3eb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[21]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr.row-new.editable.row-data > td.grid-cell.for-Create > grid-cell > formatter-component-cell > checkbox-cell > div.custom-CheckBoxHolder > input.custom-CheckBoxInput.enabled.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>708c9cbb-9f66-453e-8c0d-ef97da3a6e68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>28a14239-190b-4085-9467-041e46952592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-model</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>356e4ebb-9567-421f-a24a-0a0f4c7e78ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-class-name</name>
      <type>Main</type>
      <value>custom-CheckBoxInput enabled</value>
      <webElementGuid>10a42c26-dcd7-4784-8b08-e353cc91b503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-CheckBoxInput enabled ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>945d40c3-633d-44ae-8a78-16c528a73af5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OMS-Module-view&quot;)/div[@class=&quot;content-div col-sm-12 col-xs-12 no-padding&quot;]/div[@class=&quot;container-fluid no-padding oms-main-container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 witsml-main-module-container no-padding&quot;]/div[@class=&quot;col-md-12 acl-content-outer-container no-padding&quot;]/div[@class=&quot;acl-content-container&quot;]/div[@class=&quot;main-content-block&quot;]/div[@class=&quot;main-content-container&quot;]/acl-assignment[@class=&quot;pull-left&quot;]/div[@class=&quot;assignment-view-container col-sm-12 no-padding&quot;]/div[@class=&quot;assignment-container&quot;]/div[@class=&quot;assignment-acldetails-container&quot;]/pvu-grid[@class=&quot;basicGidView&quot;]/div[@class=&quot;pvu-grid-container&quot;]/div[@class=&quot;grid-body-container&quot;]/grid-body[1]/table[@class=&quot;grid-body table table-bordered table-hover&quot;]/tbody[1]/tr[@class=&quot;row-new editable row-data&quot;]/td[@class=&quot;grid-cell for-Create&quot;]/grid-cell[1]/formatter-component-cell[1]/checkbox-cell[1]/div[@class=&quot;custom-CheckBoxHolder&quot;]/input[@class=&quot;custom-CheckBoxInput enabled ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>eeb33409-9a2a-443e-ade9-aa0f9955e115</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[21]</value>
      <webElementGuid>421c15b5-1e00-42c6-987b-12c9578da5c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='OMS-Module-view']/div[2]/div/div/div/div/div/div[3]/div[2]/acl-assignment/div[4]/div[2]/div[3]/pvu-grid/div/div[2]/grid-body/table/tbody/tr[3]/td[5]/grid-cell/formatter-component-cell/checkbox-cell/div/input</value>
      <webElementGuid>07c52d25-1647-43bc-8db4-ed4b9158dcb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[5]/grid-cell/formatter-component-cell/checkbox-cell/div/input</value>
      <webElementGuid>a17f785a-32d6-4a22-ab70-4efe0636470d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>0a19e780-237a-4057-863a-8b1faa9c153f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
