<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CheckBoxInput_2</name>
   <tag></tag>
   <elementGuidId>44bb5c40-4a68-416d-8733-52df28a38a2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr.row-new.editable.row-data > td.grid-cell.for-Create > grid-cell > formatter-component-cell > checkbox-cell > div.custom-CheckBoxHolder > input.custom-CheckBoxInput.enabled.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[22]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8ecf61c5-ea85-4964-9789-b0afc56049bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>71e2060f-3879-4c08-adc0-be57ed13e04c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-model</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7faf3c65-a363-4e23-bc80-c012b41fa820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-class-name</name>
      <type>Main</type>
      <value>custom-CheckBoxInput enabled</value>
      <webElementGuid>c75d85c3-74c5-4251-805c-0a4f50a707b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-CheckBoxInput enabled ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>dadad6e3-4f35-4de1-805c-b8e23a031a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OMS-Module-view&quot;)/div[@class=&quot;content-div col-sm-12 col-xs-12 no-padding&quot;]/div[@class=&quot;container-fluid no-padding oms-main-container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 witsml-main-module-container no-padding&quot;]/div[@class=&quot;col-md-12 acl-content-outer-container no-padding&quot;]/div[@class=&quot;acl-content-container&quot;]/div[@class=&quot;main-content-block&quot;]/div[@class=&quot;main-content-container&quot;]/acl-assignment[@class=&quot;pull-left&quot;]/div[@class=&quot;assignment-view-container col-sm-12 no-padding&quot;]/div[@class=&quot;assignment-container&quot;]/div[@class=&quot;assignment-acldetails-container&quot;]/pvu-grid[@class=&quot;basicGidView&quot;]/div[@class=&quot;pvu-grid-container&quot;]/div[@class=&quot;grid-body-container&quot;]/grid-body[1]/table[@class=&quot;grid-body table table-bordered table-hover&quot;]/tbody[1]/tr[@class=&quot;row-new editable row-data&quot;]/td[@class=&quot;grid-cell for-Create&quot;]/grid-cell[1]/formatter-component-cell[1]/checkbox-cell[1]/div[@class=&quot;custom-CheckBoxHolder&quot;]/input[@class=&quot;custom-CheckBoxInput enabled ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>c6f44493-bb8b-4317-bb26-0b67d7140b65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[21]</value>
      <webElementGuid>02b7ad33-8df6-44ef-9335-fdf84ea0d01e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='OMS-Module-view']/div[2]/div/div/div/div/div/div[3]/div[2]/acl-assignment/div[4]/div[2]/div[3]/pvu-grid/div/div[2]/grid-body/table/tbody/tr[3]/td[5]/grid-cell/formatter-component-cell/checkbox-cell/div/input</value>
      <webElementGuid>de92f3fe-2c5b-4645-8e04-45cb76713b36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[5]/grid-cell/formatter-component-cell/checkbox-cell/div/input</value>
      <webElementGuid>8650d475-b7e7-4fd3-8b95-d75656a7ffa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>2837e433-baf3-4b8c-be57-1faf003f7491</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
