<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CheckBoxInput_5</name>
   <tag></tag>
   <elementGuidId>9046e0e5-cc4c-4fd8-8812-b2372e003afd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr.row-new.editable.row-data > td.grid-cell.for-Create > grid-cell > formatter-component-cell > checkbox-cell > div.custom-CheckBoxHolder > input.custom-CheckBoxInput.enabled.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[25]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b280fda0-26b1-4713-aa25-278740a5ad6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b1b0b300-f30c-402a-b225-1d9c85b76826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-model</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cde56a8f-7fea-451f-8cec-3d1cd0fb0063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-class-name</name>
      <type>Main</type>
      <value>custom-CheckBoxInput enabled</value>
      <webElementGuid>036b96ed-1f93-4fd9-9273-5952f18899c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-CheckBoxInput enabled ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>d63376e7-2d7b-442a-8c6a-8181149053fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OMS-Module-view&quot;)/div[@class=&quot;content-div col-sm-12 col-xs-12 no-padding&quot;]/div[@class=&quot;container-fluid no-padding oms-main-container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 witsml-main-module-container no-padding&quot;]/div[@class=&quot;col-md-12 acl-content-outer-container no-padding&quot;]/div[@class=&quot;acl-content-container&quot;]/div[@class=&quot;main-content-block&quot;]/div[@class=&quot;main-content-container&quot;]/acl-assignment[@class=&quot;pull-left&quot;]/div[@class=&quot;assignment-view-container col-sm-12 no-padding&quot;]/div[@class=&quot;assignment-container&quot;]/div[@class=&quot;assignment-acldetails-container&quot;]/pvu-grid[@class=&quot;basicGidView&quot;]/div[@class=&quot;pvu-grid-container&quot;]/div[@class=&quot;grid-body-container&quot;]/grid-body[1]/table[@class=&quot;grid-body table table-bordered table-hover&quot;]/tbody[1]/tr[@class=&quot;row-new editable row-data&quot;]/td[@class=&quot;grid-cell for-Create&quot;]/grid-cell[1]/formatter-component-cell[1]/checkbox-cell[1]/div[@class=&quot;custom-CheckBoxHolder&quot;]/input[@class=&quot;custom-CheckBoxInput enabled ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>ccf175bf-221e-470c-82d8-a9c23baa9d4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[21]</value>
      <webElementGuid>a94f8efa-f82b-4b15-9f78-c86016076e03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='OMS-Module-view']/div[2]/div/div/div/div/div/div[3]/div[2]/acl-assignment/div[4]/div[2]/div[3]/pvu-grid/div/div[2]/grid-body/table/tbody/tr[3]/td[5]/grid-cell/formatter-component-cell/checkbox-cell/div/input</value>
      <webElementGuid>128ed8ba-8151-45f6-bee9-85499773233c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[5]/grid-cell/formatter-component-cell/checkbox-cell/div/input</value>
      <webElementGuid>7ed7fbaf-9613-4a66-8f41-41f77b5bf2e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>ad3f6a73-0f55-4228-9160-049c4a532518</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
