<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_form-control input-sm input-textCls s_6a30a2</name>
   <tag></tag>
   <elementGuidId>13dd71d6-0a6a-45ac-9280-e965d942d62b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.form-control.input-sm.input-textCls.serverName.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f1ac95c6-c27d-4122-bded-761d543a334e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm input-textCls serverName ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>ea2d32c0-6506-402a-908c-581f7d07fa36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Name</value>
      <webElementGuid>126e2661-877a-4c37-9974-d975337b127f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0b769a32-8757-407a-b1ff-75f5214be600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ServerDisplayTable&quot;)/tr[@class=&quot;new-config-add&quot;]/td[1]/div[1]/input[@class=&quot;form-control input-sm input-textCls serverName ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>c6631ca1-f46a-45ae-9021-d9504dea01f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>83ec6eb1-a3e9-4856-83c1-a3e74ffbad55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='ServerDisplayTable']/tr/td/div/input</value>
      <webElementGuid>22c27047-7439-4b81-9b6a-7bf4d4901793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>03a3ea5d-18cf-43bf-b2bc-15c496ec0b36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter Name' and @type = 'text']</value>
      <webElementGuid>7afa16ad-7c7b-46b6-a2ef-8c1c824646dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
