<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CheckBoxInput_4</name>
   <tag></tag>
   <elementGuidId>ee4d7650-534e-41c4-b1c3-943fcc97fa6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr.row-new.editable.row-data > td.grid-cell.for-Create > grid-cell > formatter-component-cell > checkbox-cell > div.custom-CheckBoxHolder > input.custom-CheckBoxInput.enabled.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[24]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>845ce5c9-0d39-4634-8095-f452368c2043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>40fd96d2-ddab-4b6c-96fd-3e5762e609cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-model</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4be9cd17-7663-4f38-afe9-01bc516cef91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-class-name</name>
      <type>Main</type>
      <value>custom-CheckBoxInput enabled</value>
      <webElementGuid>1c6b1e9d-e6ed-45ef-a645-9df7fbb2b04b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-CheckBoxInput enabled ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>82c90c2a-bf2d-409a-a3d3-5522bee9f564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OMS-Module-view&quot;)/div[@class=&quot;content-div col-sm-12 col-xs-12 no-padding&quot;]/div[@class=&quot;container-fluid no-padding oms-main-container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 witsml-main-module-container no-padding&quot;]/div[@class=&quot;col-md-12 acl-content-outer-container no-padding&quot;]/div[@class=&quot;acl-content-container&quot;]/div[@class=&quot;main-content-block&quot;]/div[@class=&quot;main-content-container&quot;]/acl-assignment[@class=&quot;pull-left&quot;]/div[@class=&quot;assignment-view-container col-sm-12 no-padding&quot;]/div[@class=&quot;assignment-container&quot;]/div[@class=&quot;assignment-acldetails-container&quot;]/pvu-grid[@class=&quot;basicGidView&quot;]/div[@class=&quot;pvu-grid-container&quot;]/div[@class=&quot;grid-body-container&quot;]/grid-body[1]/table[@class=&quot;grid-body table table-bordered table-hover&quot;]/tbody[1]/tr[@class=&quot;row-new editable row-data&quot;]/td[@class=&quot;grid-cell for-Create&quot;]/grid-cell[1]/formatter-component-cell[1]/checkbox-cell[1]/div[@class=&quot;custom-CheckBoxHolder&quot;]/input[@class=&quot;custom-CheckBoxInput enabled ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>438138f0-f645-4b6e-8053-726cfa3b73c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[21]</value>
      <webElementGuid>f41ccea5-70ca-4aac-ab7d-19d12fac1f00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='OMS-Module-view']/div[2]/div/div/div/div/div/div[3]/div[2]/acl-assignment/div[4]/div[2]/div[3]/pvu-grid/div/div[2]/grid-body/table/tbody/tr[3]/td[5]/grid-cell/formatter-component-cell/checkbox-cell/div/input</value>
      <webElementGuid>dcfcdb79-b2b2-4c72-99dd-5ab7a12021e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[5]/grid-cell/formatter-component-cell/checkbox-cell/div/input</value>
      <webElementGuid>56680347-b136-4012-a9fb-e34374b1b449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>e926e686-e4bd-4367-998d-e4fc778ca391</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
