<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_save-btn</name>
   <tag></tag>
   <elementGuidId>761d3409-e2b9-436e-9b56-88d114069401</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='ServerDisplayTable']/tr/td[3]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.save-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bc0e4905-dcb2-44e1-b741-1fd6972950de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>save-btn</value>
      <webElementGuid>eba6ba9b-8c70-41d6-b860-8e08eac52dd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ServerDisplayTable&quot;)/tr[@class=&quot;new-config-add&quot;]/td[@class=&quot;button-td&quot;]/span[@class=&quot;save-btn&quot;]</value>
      <webElementGuid>c1ca5c6b-d299-4a5e-9b01-3a8a499b5749</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='ServerDisplayTable']/tr/td[3]/span</value>
      <webElementGuid>0f87b27b-5787-44aa-8ae1-3cc79eb58f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/span</value>
      <webElementGuid>9c4e3bb6-7aae-4f74-a061-22c120971900</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
