<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_samscvtech</name>
   <tag></tag>
   <elementGuidId>77e3693e-6b57-4572-b08d-29e0f415810f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='ServerDisplayTable']/tr[2]/td/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.config-text-display</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d754f568-4541-4570-9d6f-38625d6812df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>config-text-display</value>
      <webElementGuid>7628cb6f-64b9-4acc-92f9-1539f6a48058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-title</name>
      <type>Main</type>
      <value>samscvtech</value>
      <webElementGuid>656dacce-e783-4735-993e-1e10111f74c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>samscvtech</value>
      <webElementGuid>851c0b23-bfb7-4f45-b04f-e5ac8f499207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>samscvtech</value>
      <webElementGuid>1fcd5111-729a-40f9-a1c5-405f9383c809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ServerDisplayTable&quot;)/tr[@class=&quot;server-custom-row-cls&quot;]/td[1]/span[@class=&quot;config-text-display&quot;]</value>
      <webElementGuid>6a69a5b7-69a7-4826-a607-4ea60f020474</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='ServerDisplayTable']/tr[2]/td/span</value>
      <webElementGuid>5dd3401f-5c21-4796-97a0-ad9284ec827c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/span</value>
      <webElementGuid>184a8cb8-d012-4e31-903d-c89965a93327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'samscvtech' and (text() = 'samscvtech' or . = 'samscvtech')]</value>
      <webElementGuid>2ef115c1-1509-41ae-84ec-7d6602edc234</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
