<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Group</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>165f5ce0-4fcc-4fe3-806c-306b4bfdb652</testSuiteGuid>
   <testCaseLink>
      <guid>ccc19a05-2743-4587-9bd4-a67b8e2ada4c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Group/Created Update Delete/GRP01_Create_User</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1fb84b5b-afd2-4289-9cb4-5fb7df3e9b4c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f41346d-94ed-4807-a430-d73aa1456563</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>535ac263-a7fd-432d-8d2c-43b46fbfe356</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be1d12e5-7cdd-48ab-a633-c568cdec2287</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92d27da4-fc30-4d96-a2da-6e75b5e1bd12</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef30386a-6de3-4b24-9350-afacee179bfb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b363b44-73cc-4bbc-9e3f-0910e692cce5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fb9f697-2329-4679-96d6-257f38c1c6d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c5e3aa57-942d-4dba-b01c-a1b988ed8f54</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>07b4780d-ea56-4bc0-bb4a-69d319f1c12a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Group/Created Update Delete/GRP02_Create_Group</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0aec27fa-cf40-40c6-a242-b424d17af20b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f31b7f7-a636-4599-997a-f0d2532f83b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0d520b6-7482-43e1-84c2-5a8a55a314b5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2b695e09-b7a5-4400-bfc5-ebb6cc823f8c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Group/Created Update Delete/GRP04_Login_No_Access</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3d3a10d-9d68-4dd7-ace7-698284370c12</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c99d9aaf-b7a1-4e12-966a-a3b15d950994</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3abc6121-9ad0-4ff3-9550-a1789999b32e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Group/Created Update Delete/GRP05_Add_Access_OMS</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>9471f075-62f9-47e8-8794-3e29d02bfb24</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Group/Created Update Delete/GRP06_Login_Has_Access</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd401399-4259-4d92-9798-f2228b701d29</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a57bd5b-8f8b-4ec3-9f2d-afc1269ed938</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>df8775ac-749c-403f-85c5-a8c84e46ed8f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Group/Created Update Delete/GRP07_Disable_Group</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5b3ca7e-67b2-4a57-b4d8-fbff7e191a01</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>88ffe6a7-36de-4d5a-9b2c-04f621ae4c89</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Group/Filter/Group_Filter_Company</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e5712853-1565-41da-ada6-6ac30647733d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2d54321-9851-4e90-b269-42440478f49e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>da00f0c7-8ca5-4a4f-b872-7dc00f42ec5e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Group/Filter/Group_Filter_Status</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0820c42-3884-4ebb-9c77-76dfe841767f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f93fc49c-193c-443c-8fa9-e2d674b874d7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3cbfe723-17f1-4c14-b003-990d215778ea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Group/Filter/Group_Filter_Type</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0d46309-34b3-4ece-80ee-228a3c0c109b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09da24a8-e775-4aea-b278-739c5d81f22a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2f897aba-7813-48c4-9406-8ccb8e2c0bee</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Group/Group_VerifyPageAndColumn</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>efa3f20f-8610-44ec-8a1e-336b8aeb0547</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf2b9443-732b-4805-b803-1e25dd00caa8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3e0263a9-1c5b-45ae-83bd-b3acf426d4d9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Group/Search/Group_Search_Name</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d74e7ae0-00d2-44cd-b693-d356c4a73c3e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>572d819e-42ad-48b3-b348-a41ca535f528</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Group/Sort/Group_Sort_CreatedDate</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fdac659-5b3d-4508-9d46-e5213765229a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>068bb754-f16a-4a8c-a8c6-78fd2634e4cd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e54adf27-d007-4a18-84c5-e9ac96625e5d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Group/Sort/Group_Sort_ModifiedDate</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9efc9654-3d1d-4105-9b25-5e76eb2d0d04</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab372146-c1a3-46f7-a697-95ecdfea5c1c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3e8d5fb1-3b53-450e-9a6d-374922de1211</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Group/Sort/Group_Sort_Name</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c20c5681-6ba3-4c08-a68a-c220f21446ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10f8cd26-7d08-4cf4-ae3d-fa2d5b02e65e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f5c45a0c-f3db-4313-b2b1-9b341527d3f6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Group/Created Update Delete/GRP03_Update_Group</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c1e1670-d94f-4806-b155-da3c4bc646bd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>814a28e4-b034-4c13-9370-40d06ff33bae</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Group/Created Update Delete/GRP08_Delete_Group</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11b6d35d-99f1-4009-8fc9-7cffcfc7f2bc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1ae22b3e-41e2-46b7-a067-c908ebb44836</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Group/Created Update Delete/GRP09_Delete_User</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09c33690-5810-41e2-86ee-fd16a751d1be</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
