<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>User</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>a8e44fc9-ba33-4175-afb0-20f6ce82ecc9</testSuiteGuid>
   <testCaseLink>
      <guid>c2731d34-2ba8-44e6-9e49-c780827a0c2d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/User/Create Update Delete/01_Create_User</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea8023c8-3672-4309-b04e-be0fb9fa96a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d83bf120-aca9-44ec-b411-ebb63b438504</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c80b7475-e8bb-48be-8f62-e60a19e71cd6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d03da9f6-c425-4eda-b4b7-5b84853aa835</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4a86482-5b98-4eb6-ab1a-778b71ed259c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59c16f17-7f2e-4b8d-8f18-b4bca6b93f92</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>acaae302-ddb9-441d-8237-0fe97f83391b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d31f4f77-e966-4b3e-bec0-95ebfabbd162</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3aec33e2-5263-4669-9e5a-25073eba3a07</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c0aeae12-bcc5-48c5-9e60-724dcea1f020</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/User/Filter/User_Filter_Company</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4de2b0cf-c1db-40ed-9ec3-d6bbe1545c63</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60f3a28f-0358-4ac0-bac4-72ca80dd478f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>675b31b2-13a1-49b2-bd7e-2b7b9f4c34fe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/User/Filter/User_Filter_Status</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91af6df6-3743-4c59-bc8a-50874b840093</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30ec722f-5df4-47fb-8af0-02a03d3ffdeb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>74a3ac82-8ac5-4459-adbe-80ff7755c278</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/User/Filter/User_Filter_Type</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79726b60-411a-4265-a62a-dc7f29f83afa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b63df49-6d8b-4f0e-ab33-643e0e6a6674</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a6baf7bd-4df9-46ff-854f-682d6b895647</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/User/Search/User_Search_Email</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d277cc1-993e-4d9b-b344-8efedb044b7e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>231e03e4-6a82-468a-a467-ced545d2b423</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f761fd0f-f189-4581-9b22-60ef302f93d9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/User/Search/User_Search_Name</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6b71ba7-3803-4985-9598-1e005e416191</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6e81311-7787-4677-bf90-90c680862f38</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>47f5f053-0203-418c-94b7-d339d0f53db6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/User/Search/User_Search_Phone</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0626b9a6-3bab-47f8-b563-2b92540e52c7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f6040d4-0e31-452f-ad0b-13f37ba834c5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c1a45ec3-c449-45dc-9ded-b5de2ebcb516</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/User/Search/User_Search_Username</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c67654b-e2b6-40f6-af49-f50cda2dd4d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de14d95c-0478-4b3c-bece-0e59aa2dca53</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4c2e72c6-570c-4087-9f23-f3de41b3cb49</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/User/Sort/User_Sort_CreatedDate</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a77841e-0aa8-4162-ab62-6a7af36dfaf7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89e74d4e-5ee3-4bb9-ade2-95945b6f5b53</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4bea033f-cbd8-48a5-b7d3-ee500f93900e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/User/Sort/User_Sort_Email</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d28993b5-7836-433d-a904-f38942cbcc79</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f5f4921-724c-4a2a-acce-f5e70ffc7b37</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8169b28f-17c9-41a7-a08d-c3391df8468e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/User/Sort/User_Sort_ModifiedDate</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>430bb790-45bb-4789-9338-7f8fd600f83a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11b5e2ba-b124-4b93-8b43-f0679a6f1a3e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fe65eb9f-04de-4bc3-9c7d-12a719d5d816</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/User/Sort/User_Sort_Name</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ba3b1b8-26c4-4b1d-ae3b-289ae5eca91a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ae32844-1585-4a1e-a082-baf8d1702538</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f9836abb-47c0-4042-bb26-dad915970210</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/User/Sort/User_Sort_Username</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39edc62a-858f-49d4-9c90-4e3dfc447721</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b27efa45-5c76-4655-83f5-8af40385d4c3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>77f499ff-302f-4f27-b389-70e8cdb20ab0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/User/User_VerifyPageAndColumn</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec7be691-c563-4864-b26a-dd74ec8dc86c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58532e7c-1efa-490b-8cde-a47c8b009d2f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>89c643c1-2e89-4ec6-8a7d-3c3896d1b4ff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/User/Create Update Delete/02_Update_User</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0ef01a8-12c8-4413-80bd-6c2e1757a26b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>708db497-aebc-4039-8836-95019fee4cad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a106a81b-b2f5-4726-85c7-1f390b8dd760</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14fa40c5-8fd4-4777-a642-32d19573dce6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d6b0aee-f858-427f-850e-779298954f93</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8197523a-0d2d-4573-8f0a-f9c064e5c440</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d9e94e5-a9f6-42ad-8ae3-f91ce15e1bb5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8563d5db-82f6-4ee5-bf0b-b89a182d08ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbbc0bc7-8760-42d8-bf0a-d912b4379596</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>441ae7de-8447-4fc0-8cda-48cf7455db36</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/User/Create Update Delete/03_Delete_User</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a17099e-5162-4978-a9b2-1ab8345d71c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8f0688a-3439-4a3a-9c5f-049dea4932b0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a69d31c-13ae-4f24-b3e1-e3e53caeab2f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1222b6e9-d6f3-4509-9d05-e85e7bd71bd4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b4cf1f2-d908-4efb-af70-1a40568497b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52b7017e-6b03-495f-8fd4-1fe57dfc9a0d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b56bbeb-aad3-49db-aae5-04f9b8ebd9d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5287f0b0-110f-4135-8100-5f862d18ab45</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51e2c401-f9a8-4636-898a-d659110845f7</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
