<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Audit Trail</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>501fb003-1b90-4b8c-8e25-8df45c5f96b0</testSuiteGuid>
   <testCaseLink>
      <guid>0ac8d2c0-9871-418a-95a5-fc2a430501f9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Audit Trail/Audit_Verify_Page_Columns</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>a903d506-e4bd-4905-96ef-dbf62fb3378b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Audit Trail/Filter/Audit_Filter_Action</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>197fc788-65d0-4e06-b6e3-c55098c0415a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1526ae53-5649-43ef-8ab1-6c600416538c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>682feafe-974c-424a-b4cf-5a6a09eaa452</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Audit Trail/Filter/Audit_Filter_Obj_Name</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8643d9f4-00c6-4884-8061-7236e387df54</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c4ca5d1-2e17-4faa-ae47-65914de5dccd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7464d7d2-9d56-43bd-8a50-77b7b358b063</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Audit Trail/Filter/Audit_Filter_Performed_By</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73ce0ba7-f42b-4ca5-9bb1-dc2d2c088bdb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b15ffcf2-f169-4a45-aa16-86ae4dd0b8dc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bc1eb1fd-1eda-45fe-8020-c8a9e917a82e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Audit Trail/Filter/Audit_Filter_Time</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>12639f0c-4a43-4cf0-a031-982806115c17</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Audit Trail/Filter/Audit_Filter_Type</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0db56a26-ee97-4a38-95b1-0ab233b202ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e0a7886-885b-4cb1-bca8-f7cb2121985d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cfaa1a5b-e0af-484a-af8d-2b42118b089a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Audit Trail/Sort/Audit_Sort_Time</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8bd81df-34b1-40e9-a83c-a4879f762a13</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9ece967-40c2-4d5b-9f84-5432dba05dfc</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
