<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_user_company</name>
   <tag></tag>
   <elementGuidId>752a2643-35d0-4e1f-9a92-93444ae84f7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;content&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d71782ea-da09-455f-b8d2-7ae71bfe0670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e2645ba0-a3e9-4b28-9c65-09469d9dd4fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>content</value>
      <webElementGuid>a3254352-68bd-4660-91bf-a296141fae98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c82b7840-7ae0-4855-a96d-3c630da16e4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-100 h-100 drop-down-input ps-0 form-control ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>d46213e7-ad92-408f-aef0-4a0d055191a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Ej387TtuPVU3&quot;)/div[@class=&quot;align-items-center d-flex justify-content-between noBorder text-field&quot;]/input[@class=&quot;w-100 h-100 drop-down-input ps-0 form-control ng-untouched ng-pristine ng-valid ng-star-inserted&quot;]</value>
      <webElementGuid>e1b8a065-12c7-4ee4-b393-e59b13caf9a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='content']</value>
      <webElementGuid>99bf3cc5-c000-4487-9ecf-6a831703b665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Ej387TtuPVU3']/div/input</value>
      <webElementGuid>e9288c56-f9b4-4c63-81e4-185be3adbe19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//pvu-dropdown-box/div/div/input</value>
      <webElementGuid>d9df3e8f-0bc5-4321-869b-88255f816586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'content']</value>
      <webElementGuid>aab9d5a4-0b44-4269-a71f-fed0cba02ec1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
