<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_user_company_petrolink</name>
   <tag></tag>
   <elementGuidId>36a26b10-22e6-495e-9b11-46a65293b7b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;content&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@title='Petrolink']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>254be773-5721-4d0a-9598-ff4b870f9dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>21fcf7a0-d253-4825-9a63-776a53fa3d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>content</value>
      <webElementGuid>7d276256-8b34-41ac-baff-c34294b88a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ae795cb5-b3f7-4dd3-b1ff-0e9ac4b53434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-100 h-100 drop-down-input ps-0 form-control ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>17d2ef28-ed75-4d23-894f-dcfa475f90a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Ej387TtuPVU3&quot;)/div[@class=&quot;align-items-center d-flex justify-content-between noBorder text-field&quot;]/input[@class=&quot;w-100 h-100 drop-down-input ps-0 form-control ng-untouched ng-pristine ng-valid ng-star-inserted&quot;]</value>
      <webElementGuid>b35c82df-e33c-4386-846e-8bb3c300d7ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='content']</value>
      <webElementGuid>e1de55d6-98de-4099-9046-eafa88abc619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Ej387TtuPVU3']/div/input</value>
      <webElementGuid>44d0538f-4085-4216-856f-27c1d08ee281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//pvu-dropdown-box/div/div/input</value>
      <webElementGuid>d2af29a9-62ea-480d-8f9f-598be8c099f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'content']</value>
      <webElementGuid>f49c674f-f26d-40c0-834c-492d4ea5e21b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
