<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_user_company_automation_temp</name>
   <tag></tag>
   <elementGuidId>a72fc9ca-4fed-4783-bbdd-43f77fb04df3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@title='Automation Company Temp']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;content&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a5081ed7-7f8e-45d1-be39-99c8218841ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a1f3f8e3-f2bf-4340-8093-8298c8f72cb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>content</value>
      <webElementGuid>958cb225-1af9-4fe6-8436-13e94c8b3237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b6a5b589-2231-413c-b7b8-d95abb9424f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-100 h-100 drop-down-input ps-0 form-control ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>8c619134-18a4-4247-936f-d0912e621aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Ej387TtuPVU3&quot;)/div[@class=&quot;align-items-center d-flex justify-content-between noBorder text-field&quot;]/input[@class=&quot;w-100 h-100 drop-down-input ps-0 form-control ng-untouched ng-pristine ng-valid ng-star-inserted&quot;]</value>
      <webElementGuid>398f49e4-55bc-4b82-ac0e-823fa909eb67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='content']</value>
      <webElementGuid>5079659c-1f43-4d72-96fc-47033ef51e68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Ej387TtuPVU3']/div/input</value>
      <webElementGuid>415aaa12-deb3-4e1b-b1c2-1e5923d3ac6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//pvu-dropdown-box/div/div/input</value>
      <webElementGuid>4518bf25-0790-4e24-901e-2ea639e1e566</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'content']</value>
      <webElementGuid>fb861f07-f6ef-4005-8ee1-bbd3712a841a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
