<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ng-star-inserted</name>
   <tag></tag>
   <elementGuidId>94116553-df43-4301-bae1-9ac5c481834d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td/pvu-checkbox/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.checkbox-cell.select-all-cell.ng-star-inserted > pvu-checkbox.ng-star-inserted > div.pvu-checkbox.cursor-pointer > span.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5eb9a8f6-9138-4057-ac29-acbb3c3a6de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>7776b264-98c7-49a3-a859-43cf70aeb5b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/pvu-root[@class=&quot;ng-tns-c1361803851-0&quot;]/div[@class=&quot;fullscreen-container ng-tns-c1361803851-0&quot;]/div[@class=&quot;p-0 ng-tns-c1361803851-0&quot;]/pvu-main-app[@class=&quot;ng-tns-c1063071239-13 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c1063071239-13&quot;]/pvu-right-panel[@class=&quot;ng-tns-c1063071239-13 ng-trigger ng-trigger-slideInOutRightPanel&quot;]/div[@class=&quot;d-flex flex-column h-100&quot;]/div[@class=&quot;right-panel-content-container p-2 pt-0 pb-0 bg-navbar&quot;]/pvu-add-user-group-to-group[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;h-100 w-100 float-start&quot;]/div[@class=&quot;grid-holder&quot;]/pvu-grid[1]/div[@class=&quot;pvu-grid-container w-100 h-100 header-hidden-grid footer-hidden-grid ng-star-inserted&quot;]/div[@class=&quot;grid-body-container header-hidden footer-hidden&quot;]/pvu-grid-body[1]/table[@class=&quot;grid-body table table-hover&quot;]/tbody[1]/tr[@class=&quot;row-data ng-star-inserted&quot;]/td[@class=&quot;checkbox-cell select-all-cell ng-star-inserted&quot;]/pvu-checkbox[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;pvu-checkbox cursor-pointer&quot;]/span[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>c446664c-f700-4c60-bd19-0fdfc722d316</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/pvu-checkbox/div/span</value>
      <webElementGuid>8bee0641-60d9-4242-b9d5-542a3bc789d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
