<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_dropdown-btn-2</name>
   <tag></tag>
   <elementGuidId>d74330bf-54ee-491f-9e30-134d3e935cdc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//pvu-multi-select-dropdown/div/div/span)[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
