<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_group_name</name>
   <tag></tag>
   <elementGuidId>ff6dd6ed-84f2-4993-be2e-0b22c94df254</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//pvu-grid-cell-full-name/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
