<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Logout</name>
   <tag></tag>
   <elementGuidId>c96d36bb-2321-492e-b4ad-eb5697f529aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-inverse.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b65184a3-cf22-4340-ae78-3095c71e2e1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d35bb6a3-98df-4673-9f89-9e3306ff36be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-inverse ng-star-inserted</value>
      <webElementGuid>77da057c-5016-46c5-89f5-95607645efe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>54592bf5-2ba4-4eb1-b6c0-f3328e0b33e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headerComponent&quot;)/pvu-main-navigation[@class=&quot;ng-tns-c1361803851-0&quot;]/pvu-navbar[1]/nav[@class=&quot;navbar navbar-font pvu-navbar&quot;]/div[@class=&quot;navbar-right-section&quot;]/div[@class=&quot;navbar-right-sub-section d-flex align-items-center&quot;]/div[@class=&quot;navbar-menu-buttons d-flex align-items-center&quot;]/pvu-user-menu[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;position-relative user-menu&quot;]/div[@class=&quot;user-menu-box position-absolute ng-star-inserted&quot;]/div[@class=&quot;user-info row&quot;]/div[@class=&quot;col-sm-8 d-flex align-items-start justify-content-center flex-column settings&quot;]/div[@class=&quot;d-flex flex-row justify-content-start align-items-center pt-2&quot;]/button[@class=&quot;btn btn-inverse ng-star-inserted&quot;]</value>
      <webElementGuid>9e4fda79-930a-4d8d-ae5a-01e5dfe4d8ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>5051297e-f636-4456-afbe-1430d741a2e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headerComponent']/pvu-main-navigation/pvu-navbar/nav/div[5]/div/div/pvu-user-menu/div/div[3]/div/div[2]/div/button[2]</value>
      <webElementGuid>7ca92560-5818-429d-a355-cb584e54714a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>30afdac9-b5d4-4bdc-b113-94c4a5863422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Logout' or . = 'Logout')]</value>
      <webElementGuid>802f617b-4116-4a65-9a69-1abe995e93f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
