<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>col_User_Type</name>
   <tag></tag>
   <elementGuidId>1eb457f6-01aa-4b63-b0b4-fbdc14094a31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Type')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.grid-header-center.truncate-by-one-icon.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1b2f6898-100b-4ecc-a0bc-817db78c7e65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>grid-header-center truncate-by-one-icon ng-star-inserted</value>
      <webElementGuid>e6758e6b-00c1-4cb8-a38f-7b17cebd042b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Type</value>
      <webElementGuid>abb602a1-c879-427f-915a-bfc831735415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/pvu-root[@class=&quot;ng-tns-c1361803851-0&quot;]/div[@class=&quot;fullscreen-container ng-tns-c1361803851-0&quot;]/div[@class=&quot;p-0 ng-tns-c1361803851-0&quot;]/pvu-main-app[@class=&quot;ng-tns-c1063071239-7 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c1063071239-7&quot;]/div[@class=&quot;fullscreen-container ng-tns-c1063071239-7 exclude-footer-main-navbar&quot;]/div[@class=&quot;h-100 ng-tns-c1063071239-7&quot;]/div[@class=&quot;w-100 h-100 router-container ng-tns-c1063071239-7&quot;]/pvu-user[@class=&quot;ng-star-inserted&quot;]/pvu-list[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;d-flex flex-column h-100 card&quot;]/div[@class=&quot;container-full pt-2 px-3&quot;]/div[@class=&quot;position-relative&quot;]/pvu-grid[@class=&quot;d-block w-100 h-100&quot;]/div[@class=&quot;pvu-grid-container w-100 h-100 header-hidden-grid footer-hidden-grid ng-star-inserted&quot;]/div[@class=&quot;grid-title-container ng-star-inserted&quot;]/pvu-grid-title[@class=&quot;ng-tns-c663453339-8 ng-star-inserted&quot;]/table[@class=&quot;grid-title table ng-tns-c663453339-8&quot;]/thead[@class=&quot;ng-tns-c663453339-8&quot;]/tr[@class=&quot;ng-tns-c663453339-8&quot;]/th[@class=&quot;ng-tns-c663453339-8 grid-header-cell for-userType ng-star-inserted&quot;]/pvu-grid-header-cell[@class=&quot;ng-tns-c663453339-8&quot;]/div[@class=&quot;grid-header-cell&quot;]/div[@class=&quot;ng-star-inserted&quot;]/a[@class=&quot;grid-header-center truncate-by-one-icon ng-star-inserted&quot;]</value>
      <webElementGuid>57f3211a-102a-4cf3-b854-55c033e202bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Type')]</value>
      <webElementGuid>57671b69-c41c-4ebb-8b39-3768054f6693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[6]/pvu-grid-header-cell/div/div/a[2]</value>
      <webElementGuid>9b7db70b-8370-4b9b-9715-a1c36376e1f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Type' or . = 'Type')]</value>
      <webElementGuid>62fed4af-44f2-44e4-9f1e-4263031bb12a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
