<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_UTC_select</name>
   <tag></tag>
   <elementGuidId>65cb96f8-d2ae-4821-83f7-3c5a68e7a18b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.selected.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>da792b00-aaf3-42f4-98d9-b001e42d696f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selected ng-star-inserted</value>
      <webElementGuid>96b57669-0b9a-4e03-8d78-9d4dfe8d5d8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>-01:00</value>
      <webElementGuid>e8ea98d5-4e90-46b6-8210-daecdda85fa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-01:00</value>
      <webElementGuid>27277f72-2488-45ff-8916-88e1fbd303cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/pvu-root[@class=&quot;ng-tns-c1361803851-0&quot;]/pvu-footer[@class=&quot;ng-tns-c1361803851-0 ng-star-inserted&quot;]/footer[@class=&quot;footer d-flex justify-content-between align-items-center user-select-none ps-2 pe-2&quot;]/div[@class=&quot;right-block position-relative&quot;]/pvu-timezone-settings-container[@class=&quot;d-inline-block&quot;]/div[1]/div[@class=&quot;time-zone-setting-container position-absolute&quot;]/pvu-timezone-settings[1]/div[@class=&quot;time-zone-setting text-start&quot;]/div[@class=&quot;time-zone-options w-100&quot;]/div[@class=&quot;select-custom-time-zone&quot;]/pvu-dropdown-box[1]/pvu-suggestion-dropdown-box-list[@class=&quot;position-fixed ng-star-inserted&quot;]/ul[@class=&quot;ng-star-inserted&quot;]/li[@class=&quot;selected ng-star-inserted&quot;]</value>
      <webElementGuid>2611b643-91c8-42d8-81c8-dce311b56170</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/li</value>
      <webElementGuid>9ae186eb-5768-467a-945b-e524f8ab0ace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@title = '-01:00' and (text() = '-01:00' or . = '-01:00')]</value>
      <webElementGuid>2dc0f17c-26c7-4334-83a6-72b5784266ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
