<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rb_UTC_LocalTime</name>
   <tag></tag>
   <elementGuidId>988845f0-aec1-478f-b81f-5da4e16689df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.checkmark</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[contains(text(),'Local Time')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3711341e-328d-4fe9-84d9-5f0fb21e6475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkmark</value>
      <webElementGuid>d6149131-588f-44ee-bf70-6440e83651ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/pvu-root[@class=&quot;ng-tns-c1361803851-0&quot;]/pvu-footer[@class=&quot;ng-tns-c1361803851-0 ng-star-inserted&quot;]/footer[@class=&quot;footer d-flex justify-content-between align-items-center user-select-none ps-2 pe-2&quot;]/div[@class=&quot;right-block position-relative&quot;]/pvu-timezone-settings-container[@class=&quot;d-inline-block&quot;]/div[1]/div[@class=&quot;time-zone-setting-container position-absolute&quot;]/pvu-timezone-settings[1]/div[@class=&quot;time-zone-setting text-start&quot;]/div[@class=&quot;time-zone-options w-100&quot;]/div[@class=&quot;w-100 ng-star-inserted&quot;]/div[@class=&quot;w-100 ng-star-inserted&quot;]/pvu-radio-button[1]/label[@class=&quot;radio-btn-container align-top ng-star-inserted&quot;]/span[@class=&quot;checkmark&quot;]</value>
      <webElementGuid>5f8ad0fe-31be-4ebe-9f3f-75961909f03f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>f27a1d7e-5f6b-4d0a-a89b-722a84acff1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
