<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rb_UTC_CustomTime</name>
   <tag></tag>
   <elementGuidId>2814d8f3-2086-4547-9b6a-ab9d3efc4408</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[contains(text(),'Custom Time')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f57504f0-e8ad-4263-94eb-bd146373cd9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkmark</value>
      <webElementGuid>b0c4defc-e8a6-4a37-8a16-b8ed2a83b1d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/pvu-root[@class=&quot;ng-tns-c1361803851-0&quot;]/pvu-footer[@class=&quot;ng-tns-c1361803851-0 ng-star-inserted&quot;]/footer[@class=&quot;footer d-flex justify-content-between align-items-center user-select-none ps-2 pe-2&quot;]/div[@class=&quot;right-block position-relative&quot;]/pvu-timezone-settings-container[@class=&quot;d-inline-block&quot;]/div[1]/div[@class=&quot;time-zone-setting-container position-absolute&quot;]/pvu-timezone-settings[1]/div[@class=&quot;time-zone-setting text-start&quot;]/div[@class=&quot;time-zone-options w-100&quot;]/div[@class=&quot;w-100 ng-star-inserted&quot;]/div[@class=&quot;w-100 ng-star-inserted&quot;]/pvu-radio-button[1]/label[@class=&quot;radio-btn-container align-top ng-star-inserted&quot;]/span[@class=&quot;checkmark&quot;]</value>
      <webElementGuid>2e89e3a7-9964-43fc-8c84-f525484d3b53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/pvu-radio-button/label/span</value>
      <webElementGuid>771acc86-b4ef-4e67-9f3b-61e2651cc3a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
